apiVersion: v1
data:
  ISTIO_GATEWAY: kubeflow/kubeflow-gateway
  USE_ISTIO: "true"
kind: ConfigMap
metadata:
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
  name: notebook-controller-config-m44cmb547t
  namespace: kubeflow
